[[mounts]]
source = "content"
target = "content"

[[mounts]]
source = "content-pagescms"
target = "content/post"

[[mounts]]
source = "content-legacy"
target = "content/post"

[[mounts]]
source = "content-photos"
target = "content/post"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "static/img"
target = "assets/img"
