#+title: Bang-Bang (!!, !$) Shell Shortcuts in Elvish
#+date: 2017-12-04T22:15:04+01:00
#+featured_image: /images/elvish-logo.svg
#+tags: elvish shell unix config
#+summary: How to set up the bash !! and !$ shortcuts for accessing the previous command in Elvish.

The bash shortcuts (maybe older? I'm not sure in which shell these
originated) for "last command" (=!!=) and "last argument of last
command" (=!$=) are, for me at least, among the most strongly imprinted
in my muscle memory, and I use them all the time. Although these
shortcuts are not available in [[/post/elvish-an-awesome-unix-shell/][Elvish]] by default, they are easy to
implement. I have written a module called [[https://github.com/zzamboni/vcsh_elvish/blob/master/.elvish/lib/bang-bang.org][bang-bang]] which you can
readily use as follows:

- Store [[https://github.com/zzamboni/vcsh_elvish/blob/master/.elvish/lib/bang-bang.elv][bang-bang.elv]] in your =~/.elvish/lib/=.
- In your =rc.elv= (see [[/post/elvish-an-awesome-unix-shell/][mine]] as an example), add the following:

  #+BEGIN_SRC elvish
    use bang-bang
    bang-bang:bind-trigger-keys
  #+END_SRC

That's it! In your new shells, command-history mode will be invoked by
the =!= key. Assuming your last command was =ls -l ~/.elvish/rc.elv=, when
you press =!= you will see the following:

#+BEGIN_EXAMPLE
  bang-lastcmd [A C] _
  ! ls -l .elvish/rc.elv
  0 ls
  1 -l
  2/$ .elvish/rc.elv
  Alt-! !
#+END_EXAMPLE

If you press =!= again, the whole last command will be inserted. If you
press =$= (or =2=), only the last argument will be inserted. You can
insert any other component of the previous command using its
corresponding number. If you want to insert an exclamation sign, you
can press =Alt-!=.

Note that by default, =Alt-!= will also be bound to trigger this mode,
so you can fully replace the default [[https://elvish.io/learn/cookbook.html]["last command" mode]] in Elvish.

Have fun with Elvish!
