#!/bin/bash

CMDUSAGE="[hugo options...]"
CMDDESC="Build and deploy on remote server"
PROGPATH=$(dirname $0)
ROOT="$(readlink -f $PROGPATH/..)"
PUBLIC="$ROOT/public"
CONF="$PROGPATH/ftp-config.json"

install_node_module() {
  for i in $@; do
     [ ! -d "node_modules/$i" ] && npm install $i
  done
}


if [ ! -e "$CONF" ]; then
  cat <<EOF
Error! You must create $CONF file first

TIP: How to create $CONF sample file

echo '{
  "host": "ftp.example.com",
  "port": 21,
  "dest": "/www",
  "username": "*****",
  "password": "*****"
}' > $CONF

EOF
  exit 1
fi

HOST=$(node -e "console.log(require('$CONF').host);")
PORT=$(node -e "console.log(require('$CONF').port);")
DEST=$(node -e "console.log(require('$CONF').dest);")
USERNAME=$(node -e "console.log(require('$CONF').username);")
PASSWORD=$(node -e "console.log(require('$CONF').password);")

echo "# Setup"
tmp=$PWD
cd $PROGPATH
install_node_module ftpsync
cd $tmp
echo "OK"

echo
echo "# Building"
hugo --source=$ROOT --config=$ROOT/config.toml $@

echo
echo "# Deployement on $HOST:$PORT (under $DEST)"
$PROGPATH/node_modules/ftpsync/bin/ftpsync -l $PUBLIC -r $DEST -h $HOST -p $PORT -u $USERNAME -s $PASSWORD -c 10 -v
